services:
  db:
    image: postgres:16
    container_name: backproject_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123
      POSTGRES_DB: backProject
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: backproject_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data:
